version: '3.8'

services:
  app:
    build: .
    container_name: app-node
    ports:
      - "3001:3000"  # <-- alterei aqui: host 3001 para container 3000
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - DB_CONNECTION_STRING=mongodb://mongo:27017/BlogPostagens
    depends_on:
      - mongo

  mongo:
    image: mongo:6
    container_name: mongo-db
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
